### ISSUE TITLE
DockerStats collector crashes

### ISSUE THREAD

**Issue by ChristianKniep** [qnib/QNIBCollect#29]
Somehow the DockerStats collector does not close the file handles and crashes. :)

```
time="08 Jun 16 00:48 UTC" level=info msg="POST of 1 metrics to InfluxDB took 0.000272 seconds" app=fullerite handler=InfluxDB pkg=handler
time="08 Jun 16 00:48 UTC" level=info msg="POST of 8 metrics to InfluxDB took 0.000591 seconds" app=fullerite handler=InfluxDB pkg=handler
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a138a]

goroutine 6 [running]:
fullerite/collector.(*DockerStats).Collect(0xc82007b9e0)
        /data/src/fullerite/collector/docker_stats.go:127 +0xaea
main.runCollector(0x7f17cc081ad0, 0xc82007b9e0)
        /data/src/fullerite/collectors.go:73 +0x30e
created by main.startCollector
        /data/src/fullerite/collectors.go:51 +0x260
```

**Comment by ChristianKniep** [comment]
Was due to the InfluxDB handler. Fixed #32
